apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
data:
  PORT: "5554"
  MONGOURI: "mongodb+srv://susadisandanima:HwHKte2tbJQUNqyy@cluster0.uew09.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  AUTH_SVC_URL: "http://restaurant-admin-service:5556/api/auth"
  ORDER_SVC_URL: "http://order-service:5557/api/orders"
